[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
upd_sbc = "GCGcqanABcRwwfVXyma59p8H1mX7KPNLwodbdG9Ee1g7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/fpalfonso/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
